// Package model defines the provider-agnostic types shared by every source
// parser, the indexer and the query layer.
package model

import "time"

// Kind classifies a message. Every source maps its own record types onto
// this closed set so that search filters behave identically across agents.
type Kind string

const (
	KindPrompt     Kind = "prompt"      // text the human actually typed
	KindReply      Kind = "reply"       // assistant prose
	KindThink      Kind = "think"       // assistant reasoning
	KindCommand    Kind = "command"     // slash-command invocation
	KindToolUse    Kind = "tool_use"    // tool call arguments
	KindToolResult Kind = "tool_result" // tool output
	KindMeta       Kind = "meta"        // injected context, interruptions
	KindSystem     Kind = "system"      // system events
	KindSummary    Kind = "summary"     // context-compaction summary
)

// AllKinds lists every kind in a stable order.
var AllKinds = []Kind{
	KindPrompt, KindReply, KindThink, KindCommand, KindSummary,
	KindToolUse, KindToolResult, KindMeta, KindSystem,
}

// DefaultKinds are searched unless the caller asks for more.
var DefaultKinds = []Kind{KindPrompt, KindReply, KindThink, KindCommand, KindSummary}

// ValidKind reports whether k is a known kind.
func ValidKind(k Kind) bool {
	for _, v := range AllKinds {
		if v == k {
			return true
		}
	}
	return false
}

// Message is one searchable unit of conversation. A single raw record may
// produce several messages (e.g. an assistant turn with text + tool calls).
type Message struct {
	SessionID  string
	AgentID    string // non-empty for sub-agent (sidechain) records
	Slug       string // sub-agent type, when known
	UUID       string
	ParentUUID string
	Time       time.Time
	Role       string // user | assistant | system
	Kind       Kind
	Tool       string // tool name for tool_use
	CWD        string
	Branch     string
	Text       string

	Model        string // model that produced an assistant message
	RequestID    string // API request an assistant message belongs to
	ToolUseID    string // links a tool_use to its tool_result
	IsError      bool   // tool_result reported an error
	PromptSource string // how a prompt was entered (typed, queued, …)
	FilePath     string // file a tool call operates on

	// Invocation fields are set on messages that invoke something by name:
	// a slash command the user typed, a skill or a sub-agent the model
	// started.
	InvKind string // "command", "skill" or "subagent"
	InvName string // without a leading "/"
	InvArgs string // what followed the name
}

// Invocation kinds.
const (
	InvCommand  = "command"
	InvSkill    = "skill"
	InvSubagent = "subagent"
)

// Usage is the token accounting of one API request. A request may be
// spread over several raw lines; the one with the most output wins.
type Usage struct {
	RequestID    string
	SessionID    string
	AgentID      string
	Model        string
	CWD          string
	Branch       string
	Time         time.Time
	Input        int64 // uncached input tokens
	Output       int64
	CacheRead    int64
	CacheWrite5m int64
	CacheWrite1h int64
	Thinking     int64 // part of Output, when reported
}

// Turn is one completed agent turn (user input to final answer).
type Turn struct {
	SessionID  string
	AgentID    string
	CWD        string
	Branch     string
	Time       time.Time
	DurationMs int64
	Messages   int64
}

// SessionCost is the cumulative accounting an agent reports for a session.
type SessionCost struct {
	USD          float64
	LinesAdded   int64
	LinesRemoved int64
	DurationMs   int64
}

// Title priorities: a higher rank wins over a lower one; equal ranks let
// the later record win.
const (
	TitleRankAuto   = 1 // generated by the agent
	TitleRankCustom = 2 // set by the user
)

// SessionMeta carries session-level facts that are not messages.
type SessionMeta struct {
	SessionID string
	Title     string // empty when the record carries no title
	TitleRank int
	Cost      *SessionCost // latest cumulative cost, when reported
}

// Parsed is everything one raw line contributes to the index.
type Parsed struct {
	Messages []Message
	Meta     *SessionMeta
	Usage    *Usage
	Turn     *Turn
}

// Source is a pluggable conversation-history provider (Claude Code, Codex…).
// Implementations must be safe to call concurrently.
type Source interface {
	// Name is the short identifier stored in the `source` column.
	Name() string
	// Roots are the directories scanned for history files.
	Roots() []string
	// Match reports whether path is a history file owned by this source.
	Match(path string) bool
	// ProjectOf derives a project name from a file path.
	ProjectOf(path string) string
	// ParseLine parses one raw line. It is stateless: the same line always
	// yields the same result regardless of what came before it.
	ParseLine(line []byte) (Parsed, error)
}

// FileSource is implemented by sources whose lines only make sense together
// with earlier lines of the same file. Codex, for example, writes the session
// id and working directory once at the top and the model once per turn. The
// indexer then parses a file through a FileParser instead of ParseLine.
type FileSource interface {
	Source
	// OpenFile returns a parser for one file. Parsing starts at byte
	// resumeAt, which is past the lines indexed earlier; the parser may read
	// those leading bytes to recover the state they established.
	OpenFile(path string, resumeAt int64) (FileParser, error)
}

// FileParser parses the lines of one file in order. It is used by a single
// goroutine.
type FileParser interface {
	ParseLine(line []byte) (Parsed, error)
}
