// Package model defines the provider-agnostic types shared by every source
// parser, the indexer and the query layer.
package model

import "time"

// Kind classifies a message. Every source maps its own record types onto
// this closed set so that search filters behave identically across agents.
type Kind string

const (
	KindPrompt     Kind = "prompt"      // text the human actually typed
	KindReply      Kind = "reply"       // assistant prose
	KindThink      Kind = "think"       // assistant reasoning
	KindCommand    Kind = "command"     // slash-command invocation
	KindToolUse    Kind = "tool_use"    // tool call arguments
	KindToolResult Kind = "tool_result" // tool output
	KindMeta       Kind = "meta"        // injected context, interruptions
	KindSystem     Kind = "system"      // system events
	KindSummary    Kind = "summary"     // context-compaction summary
)

// AllKinds lists every kind in a stable order.
var AllKinds = []Kind{
	KindPrompt, KindReply, KindThink, KindCommand, KindSummary,
	KindToolUse, KindToolResult, KindMeta, KindSystem,
}

// DefaultKinds are searched unless the caller asks for more.
var DefaultKinds = []Kind{KindPrompt, KindReply, KindThink, KindCommand, KindSummary}

// ValidKind reports whether k is a known kind.
func ValidKind(k Kind) bool {
	for _, v := range AllKinds {
		if v == k {
			return true
		}
	}
	return false
}

// Message is one searchable unit of conversation. A single raw record may
// produce several messages (e.g. an assistant turn with text + tool calls).
type Message struct {
	SessionID  string
	AgentID    string // non-empty for sub-agent (sidechain) records
	Slug       string // sub-agent type, when known
	UUID       string
	ParentUUID string
	Time       time.Time
	Role       string // user | assistant | system
	Kind       Kind
	Tool       string // tool name for tool_use
	CWD        string
	Branch     string
	Text       string
}

// Title priorities: a higher rank wins over a lower one; equal ranks let
// the later record win.
const (
	TitleRankAuto   = 1 // generated by the agent
	TitleRankCustom = 2 // set by the user
)

// SessionMeta carries session-level facts that are not messages.
type SessionMeta struct {
	SessionID string
	Title     string
	TitleRank int
	CWD       string
	Branch    string
}

// Source is a pluggable conversation-history provider (Claude Code, Codex…).
// Implementations must be safe to call concurrently.
type Source interface {
	// Name is the short identifier stored in the `source` column.
	Name() string
	// Roots are the directories scanned for history files.
	Roots() []string
	// Match reports whether path is a history file owned by this source.
	Match(path string) bool
	// ProjectOf derives a project name from a file path.
	ProjectOf(path string) string
	// ParseLine parses one raw line. It is stateless: the same line always
	// yields the same result regardless of what came before it.
	ParseLine(line []byte) ([]Message, *SessionMeta, error)
}
